[package]
name = "moc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.19"

rand    = "*"
log     = "*"
primes = "0.4.0"
